#Python Casting (Terkadang Anda mungkin ingin menentukan tipe data pada sebuah variabel. Hal ini dapat dilakukan dengan melakukan casting)
#int() - membuat bilangan bulat dari literal bilangan bulat, literal bilangan pecahan (dengan menghilangkan semua desimal), atau literal string (dengan syarat string tersebut merupakan bilangan bulat)
x = int(20)
y = int(4.0)
z = int("3")
print(x)
print(y)
print(z)

#float() - membuat bilangan float dari literal bilangan bulat, literal float, atau literal string (dengan syarat string tersebut mewakili float atau bilangan bulat)
x = float(10)
y = float(12.0)
z = float("2")
print(x)
print(y)
print(z)

#str() - membuat string dari berbagai macam tipe data, termasuk string, literal bilangan bulat, dan literal bilangan pecahan
x = str("jes")
y = str(3)
z = str(2.0)
print(x)
print(y)
print(z)
